

from WordsInOceanOfLetters import WordsInOceanOfLetters

# ImagePath = 'C:\\Users\\sai.kurakula\\Desktop\\words.jpg'
# TesseractPath = 'C:\\Users\\sai.kurakula\\Desktop\\Tesseract\\tesseract.exe'
BASEDIR = 'E:\\PyCharm\\WordsInOceanOfLetters\\Word lists in csv\\'
# fileName = 'Aword.csv'
# pandas_data = pd.read_csv(os.path.join(BASEDIR,fileName),sep='delimiter',header=None)

# has_data = pandas_data[pandas_data[0].str.startswith('aetiology') == True].drop_duplicates()

# print(has_data.__len__())
# print(pandas_data[:0].filter(like='ae',axis=1))

# pytesseract.pytesseract.tesseract_cmd = TesseractPath
data = """
JGLDMGkDMSDOEOYMSCMWOQPRYTLSMLFJOMCES
KOGJKLMSMIEOPJMLSMVMGKEJSKNMLESSONSJAPQ
PEICREATIONJMXLAMFAJFLSMCGJIWLPVEPJFLAMVL
WILFEGMLEMFMEPAVBNZLSNVMJDKUITEWJTKDKNV
MSAGKDSLJGKDLSJGKLSGRATITUDEJGKLSJAKLGZV
NMCNSJWUQDLDPWSJGDSKlEMNBSKGMNBAXBDMSII
IMELNGSANVDCONNECTIONKMGEWJNNZCMANHHFL
NQIRPWIQTYIEJCZXNMXZVJSAGKSMZNVLGKELJWJK
TNSNJDQRWADFXCRPWVGCRBYTNMONEYKUMLIMLY
UJVRNWCGEYVQPOWERPUYXDRWKLJDSKLGJKDSLJI
IALIGNMENTJEVMSLJJFLSHAHMLFJELWPORIVMSMM
TGLDMGKDMSIOMCHANGEVVMSCMWOQPRYTLSMLFJ
IJMCESKOGJKLMSMIEOPJMLSMVMGKEJSKNMJAPQPE
OOMXLAMFAHEALTHJFLSMCGJIWPJFLAMVLWILFEGM
NNMFMEPAVBNZLSNVMJDKUISELFCAREVMSNGKDSL
JGKDLSJGKLSJGKLSJAKLGZVNMCNSJWUQDLDPWSJ
GDSKIEMNBSKGMNBAXBDMSGMELNGSANVDSMGEW
JNNZCMANHHFLSTRENGTHWQIRPWIQTYIEJCZXNMR
ZVJSAGKSMZNVLGKELJWJKCNSNFAMILYJDQRWADE
XCRSWVGCRBYTNKUMLIMLYBJVRNWCGEYVQXDRWS
LJDSKLWPURPOSEJKDSLJEMJGLDMGKDMSDOEOVM
STMWOQMIRACLESPRYTLSMLFJOMCESKOGJKLMSMI
ELPJMLSMVMGKEJSKNMJAPQBREAKTHROUGHPEjJM
XLAMFAJFLSGMDTVNMWURHDKABNPOIUMAFNHAKHJ
JJHJJDHJSWIIRUMAMBQGEHJAKQWHCSANKNLALADI
"""
# print(pytesseract.image_to_string(Image.open(ImagePath)))
# dataArray = data.split('\n')


data = WordsInOceanOfLetters(data,BASEDIR)

print(data.getWordsFromLine())
